# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Plant a Post
tagline:          ''
description:      'Offical blog of <a href="https://plantapage.com">Plant a Page</a>.'
url:              https://blog.plantapage.com/
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
